name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: pr-validation-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Detect Changed Services
        id: set-matrix
        run: ./scripts/detect_changed_services.sh

  service-lint:
    needs: detect-changes
    if: needs.detect-changes.outputs.matrix != '[]'
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    uses: ./.github/workflows/reusable-lint.yml
    with:
      service: ${{ matrix.service }}

  service-test-cases:
    needs: [service-lint,detect-changes]
    if: needs.detect-changes.outputs.matrix != '[]'
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    uses: ./.github/workflows/reusable-test-cases.yml
    with:
      service: ${{ matrix.service }}

  service-sonar-scan:
    needs: [detect-changes,service-test-cases]
    if: needs.detect-changes.outputs.matrix != '[]'
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    uses: ./.github/workflows/reusable-sonar-scan.yml
    secrets: inherit
    with:
      service: ${{ matrix.service }}

  services-build:
    needs: [detect-changes,service-sonar-scan]
    if: needs.detect-changes.outputs.matrix != '[]'
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    uses: ./.github/workflows/reusable-docker-build.yml
    secrets: inherit
    with:
      service: ${{ matrix.service }}
      image_name: gnishanth777/online_boutique
