name: Reusable Lint Workflow

on:
    workflow_call:
        inputs:
            service:
                required: true
                type: string

jobs:
    lint:
        runs-on: ubuntu-latest
        env:
          SERVICE_PATH: ${{ inputs.service == 'cartservice' && 'src/cartservice/src' || format('src/{0}', inputs.service) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                fetch-depth: 0

            - name: Setup Go
              if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
              uses: actions/setup-go@v5
              with:
                go-version: '1.25'

            - name: Install GolangCI-Lint
              if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
              run: |
                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
                | sh -s -- -b /usr/local/bin v1.64.8

            - name: Run GolangCI-Lint
              if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
              continue-on-error: true
              working-directory: ${{ env.SERVICE_PATH }}
              run: |
                golangci-lint run ./... 2>&1 | tee golangci-report.txt || true

            - name: Upload golangCi Report
              if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
              uses: actions/upload-artifact@v6
              with:
                name: ${{ inputs.service}}-golangci-report
                path: ${{ env.SERVICE_PATH }}/golangci-report.txt

            # Nodejs Lint
            - name: Setup Node
              if: contains(fromJson('["paymentservice","currencyservice"]'), inputs.service)
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install Node Dependencies
              if: contains(fromJson('["paymentservice","currencyservice"]'), inputs.service)
              working-directory: ${{ env.SERVICE_PATH }}
              run: npm install

            - name: Run Node Lint
              if: contains(fromJson('["paymentservice","currencyservice"]'), inputs.service)
              working-directory: ${{ env.SERVICE_PATH }}
              continue-on-error: true
              run: |
                npm run lint 2>&1 | tee eslint-report.txt || true

            - name: Upload Node Lint Report
              if: contains(fromJson('["paymentservice","currencyservice"]'), inputs.service)
              uses: actions/upload-artifact@v4
              with:
                name: ${{ inputs.service }}-eslint-report
                path: ${{ env.SERVICE_PATH }}/eslint-report.txt

            # Python Lint
            - name: Setup Python
              if: contains(fromJson('["recommendationservice","emailservice"]'), inputs.service)
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install Python Lint Tools
              if: contains(fromJson('["recommendationservice","emailservice"]'), inputs.service)
              run: |
                pip install flake8 black

            - name: Install Python Lint Tools
              if: contains(fromJson('["recommendationservice","emailservice"]'), inputs.service)
              run: |
                pip install flake8 black

            - name: Run Python Lint
              if: contains(fromJson('["recommendationservice","emailservice"]'), inputs.service)
              working-directory: ${{ env.SERVICE_PATH }}
              continue-on-error: true
              run: |
                flake8 . 2>&1 | tee flake8-report.txt || true
                black --check . | tee black-report.txt || true

            - name: Upload Python Lint Report
              if: contains(fromJson('["recommendationservice","emailservice"]'), inputs.service)
              uses: actions/upload-artifact@v6
              with:
                name: ${{ inputs.service }}-python-lint-report
                path: |
                  ${{ env.SERVICE_PATH }}/flake8-report.txt
                  ${{ env.SERVICE_PATH }}/black-report.txt

            # Dotnet Lint
            - name: Setup Dotnet
              if: inputs.service == 'cartservice'
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'

            - name: Run Dotnet Format Check
              if: inputs.service == 'cartservice'
              continue-on-error: true
              working-directory: ${{ env.SERVICE_PATH }}
              run: |
                dotnet format --verify-no-changes 2>&1 | tee dotnet-formate-report.txt || true

            - name: Upload Dotnet Lint Report
              if: inputs.service == 'cartservice'
              uses: actions/upload-artifact@v6
              with:
                name: cartservice-dotnet-format-report
                path: ${{ env.SERVICE_PATH }}/dotnet-formate-report.txt

