name: Reusable Docker Build and Publish

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    concurrency:
      group: docker-${{ inputs.service }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
      security-events: write
    env:
      SERVICE_PATH: ${{ inputs.service == 'cartservice' && 'src/cartservice/src' || format('src/{0}', inputs.service) }}

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Secret Scanning
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      # Dockerfile Lint
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        continue-on-error: true
        with:
          dockerfile: ${{ env.SERVICE_PATH }}/Dockerfile

      # Docker Metadata
      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ inputs.image_name }}
          tags: |
            type=raw,value=${{ inputs.service }}-latest
            type=raw,value=${{ inputs.service }}-pr-${{ github.event.number }}
            type=semver,pattern=${{ inputs.service }}-{{version}}

      # Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Docker Build
      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v7
        with:
          context: ${{ env.SERVICE_PATH }}
          file: ${{ env.SERVICE_PATH }}/Dockerfile
          push: false
          outputs: type=oci,dest=/tmp/${{ inputs.service }}.tar
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Filesystem Vulnerability Scan
      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: ${{ env.SERVICE_PATH }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          input: /tmp/${{ inputs.service }}.tar
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
          scanners: vuln

      # SBOM Generation
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          file: /tmp/${{ inputs.service }}.tar
          format: spdx-json
          output-file: sbom.spdx.json

      # Upload SBOM
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.service }}-sbom
          path: sbom.spdx.json

       # Load OCI Image
      - name: Load OCI Image
        run: |
          docker load --input /tmp/${{ inputs.service }}.tar

      # Docker Login
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker Image
      - name: Push Docker Images
        run: |
          while read tag; do
            docker push "$tag"
          done <<< "${{ steps.meta.outputs.tags }}"

      # Artifact Attestation
      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: docker.io/${{ inputs.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
