name: Reusable Test Cases Go, Dot net

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SERVICE_PATH: src/${{ inputs.service }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ########################################################
      # Runtime Setup
      ########################################################

      - name: Setup Go
        if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Setup Node
        if: contains(fromJson('["paymentservice","currencyservice"]'), inputs.service)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        if: contains(fromJson('["recommendationservice","emailservice"]'), inputs.service)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Java
        if: inputs.service == 'adservice'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Dotnet
        if: inputs.service == 'cartservice'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      ########################################################
      # Dependency Install
      ########################################################

      - name: Go Dependencies
        if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
        working-directory: ${{ env.SERVICE_PATH }}
        run: go mod download

      - name: Node Dependencies
        if: contains(fromJson('["paymentservice","currencyservice"]'), inputs.service)
        working-directory: ${{ env.SERVICE_PATH }}
        run: npm install

      - name: Python Dependencies
        if: contains(fromJson('["recommendationservice","emailservice"]'), inputs.service)
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          pip install -r requirements.txt

      - name: Java Dependencies
        if: inputs.service == 'adservice'
        working-directory: ${{ env.SERVICE_PATH }}
        run: chmod +x gradlew && ./gradlew dependencies

      - name: Dotnet Restore
        if: inputs.service == 'cartservice'
        working-directory: ${{ env.SERVICE_PATH }}/src
        run: dotnet restore
      
      ########################################################
      # Go Test Executions
      ########################################################

      - name: Run Go Test Cases
        if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          go test -v -coverprofile=coverage.out ./... | tee test-output.txt

      - name: Go Coverage Summary
        if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          go tool cover -func=coverage.out | tee coverage-summary.txt

      - name: Generate Go HTML Coverage Report
        if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload Go Coverage Report
        if: contains(fromJson('["frontend","checkoutservice","shippingservice","productcatalogservice"]'), inputs.service)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.service }}-coverage-report
          path: ${{ env.SERVICE_PATH }}/coverage.html
      
      ########################################################
      # Dotnet Test Cases Execution
      ########################################################

      - name: Run Dotnet Test Cases
        if: inputs.service == 'cartservice'
        working-directory: ${{ env.SERVICE_PATH }}/tests
        run: |
          dotnet test --collect:"XPlat Code Coverage" | tee dotnet-test-output.txt 